### PR TITLE
use scrollspy 3.3

### PR DESCRIPTION
**Pull request by yaneq**

### CODE REVIEW

**Comment by jcgt** [comment]
Hi Jan, Christof, Daniel

I've been getting emails from github with your pull requests. I am guessing
this should not be the case yes? :)

--Carlo Tubadeza

**Comment by eriklacson** [comment]
+1 on this. :-)

Cheers!

Erik
---------- Forwarded message ----------

**Comment by yaneq** [comment]
You guys might have subscribed to updates to this repo (good!), which explains the mails. We will retire this repo in the next weeks however.

**Comment by christofdamian** [comment]
this is a public repo, so not really a problem

**Pull request merged**
